### ISSUE TITLE
D-YAML package outdated

### ISSUE THREAD

**Issue by Timoses** [katafrakt/stringex-d#1]
The dyaml repo appears to be inactive. See here: https://github.com/kiith-sa/D-YAML/issues/48

Since there is no response from the maintainer I was wondering whether it is possible to move the dependency of stringex to https://code.dlang.org/packages/dyaml-dlang-tour .

**Comment by katafrakt** [comment]
Hi! Thank you for bringing my attention to this. Dependency has been changed in [this](https://github.com/katafrakt/stringex-d/commit/155282a5a9b5fa28971eeef44694f6f6708f921a) commit.
